[SliderServer]
port = 7070
host = "0.0.0.0"
server_timing_header = true
exclude = [
    "tools/jupyter conversion script.jl",
]

[Export]
baked_state = false
baked_notebookfile = false
# create_pluto_featured_index = true
slider_server_url = "https://surfer-mlss.bmlip.nl/"
exclude = [
    "tools/jupyter conversion script.jl",
]
number_of_parallel_tasks=4

